# Copyright 2025 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/ios/rules.gni")
import("//ios/build/chrome_build.gni")

ios_appex_bundle("vortex_vpn_extension") {
  sources = [
    "packet_tunnel_provider.h",
    "packet_tunnel_provider.mm",
  ]
  
  info_plist = "Info.plist"
  entitlements_path = "entitlements.plist"
  
  bundle_identifier = "$ios_app_bundle_id_prefix.VortexVPN"
  
  deps = [
    "//base",
    "//ios/chrome/common",
  ]
  
  frameworks = [
    "Foundation.framework",
    "NetworkExtension.framework",
    "Security.framework",
  ]
  
  configs += [ "//build/config/compiler:enable_arc" ]
}